defmodule FlashtonesWeb.SitemapHTML do
  use FlashtonesWeb, :html

  embed_templates "sitemap_html/*"

  # list pages with sigil_p for compile-time checking
  def pages do
    [
      # application
      ~p"/mail",
      ~p"/ft/kontakt",
      ~p"/",
      ~p"/ft",
      ~p"/ft/aktuality",
      ~p"/ft/faq",
      ~p"/faq",
      ~p"/ft/kontakty",
      ~p"/kontakty",
      ~p"/kontakty-formular",
      ~p"/ft/about",
      ~p"/ft/produkty",
      ~p"/ft/studio",
      ~p"/o-nas",
      ~p"/plavani/o-nas",
      ~p"/o-nas/historie",
      ~p"/plavani/o-nas/historie",
      ~p"/o-nas/lide",
      ~p"/plavani/o-nas/lide",
      ~p"/o-nas/spolecnost",
      ~p"/plavani/o-nas/spolecnost",
      ~p"/lyzovani/about",
      ~p"/enviro/about",
      ~p"/vylety/about",
      ~p"/doma/about",
      ~p"/academy/about",
      ~p"/reference",
      ~p"/ft/sluzby",
      ~p"/ft/hodnoceni",
      ~p"/academy",
      ~p"/academy/courses",
      ~p"/courses/school",
      ~p"/lokality",
      ~p"/plavani/lokality",
      ~p"/lyzovani/lokality",
      ~p"/enviro/lokality",
      ~p"/doma",
      ~p"/doma/courses",
      ~p"/enviro",
      ~p"/enviro/courses",
      ~p"/lyzovani",
      ~p"/lyzovani/courses",
      ~p"/plavani",
      ~p"/plavani/verejnost",
      ~p"/plavani/skolni-pobytovy-plavecky-kurz",
      ~p"/plavani/predskolni-plavecky-kurz",
      ~p"/plavani/primestsky-skolni-plavecky-kurz",
      ~p"/plavani/sobotni-kurzy-plavani",
      ~p"/plavani/services/pravidelne-kurzy-plavani/",
      ~p"/plavani/summer-camp",
      ~p"/plavani/letni-primestske-tabory",
      ~p"/plavani/services/letni-primestske-tabory/",
      ~p"/plavani/services/letni-tabor/",
      ~p"/plavani/individualni-kurzy",
      ~p"/plavani/services/vikendove-primestske-tabory-plavani/",
      ~p"/lyzovani/skolni-lyzarsky-kurz",
      ~p"/lyzovani/bezky",
      ~p"/lyzovani/weekend",
      ~p"/vylety",
      ~p"/vylety/priroda/aves-brandysek",
      ~p"/vylety/priroda/centrum-jaromer",
      ~p"/vylety/priroda/ekocentrum-huslik",
      ~p"/vylety/priroda/ekocentrum-hulice",
      ~p"/vylety/priroda/stanice-hrachov",
      ~p"/vylety/priroda/motylarium-votice",
      ~p"/vylety/priroda/ekocentrum-vlasim",
      ~p"/vylety/priroda/kurz-remesel",
      ~p"/enviro/svp",
      ~p"/enviro/tym",
      ~p"/enviro/ss-tym",
      ~p"/enviro/letni-pobytove-tabory",
      ~p"/enviro/letni-primestske-tabory-v-tymu",
      ~p"/enviro/primestske-tabory-enviro",
      ~p"/enviro/evp",
      # ~p"/lektori",
      # ~p"/lektori/manual-fotky",
      # ~p"/lektori/vecerni-programy",
      # ~p"/lektori/sportovni-doplnkovy-program",
      # ~p"/lektori/svp-instruktor",
      # ~p"/lektori/svp-hlavni-instruktor",
      # ~p"/lektori/schuze-hlavnich-instruktoru",
      # ~p"/lektori/prezencni-list",
      # ~p"/lektori/plavani-zasobnik",
      # ~p"/lektori/plavani-pirati",
      # ~p"/lektori/plavani-chobotnice",
      # ~p"/lektori/plavani-vodni-zachrana",
      # ~p"/lektori/plavani-namornici",
      # ~p"/lektori/plavani-delfini",
      # ~p"/lektori/plavani-prirucka-instruktora",
      # ~p"/lektori/enviro-metodika",
      # ~p"/lektori/enviro-metodika-starsi",
      # ~p"/lektori/tym-autismus",
      # ~p"/lektori/tym-zakladni-info",
      # ~p"/lektori/tym-sbornik",
      # ~p"/lektori/tym-enviro-aktivity-starsi",
      ~p"/aktivity",
      ~p"/ratings",
      ~p"/vylety/courses",
      ~p"/vylety/berlin",
      ~p"/vylety/boleslav",
      ~p"/vylety/drazdany",
      ~p"/vylety/kutna-hora",
      ~p"/vylety/mnichov",
      ~p"/vylety/osvetim",
      ~p"/vylety/praha",
      ~p"/vylety/tabor",
      ~p"/vylety/terezin",
      ~p"/vylety/viden",
      ~p"/lokality/agri",
      ~p"/lokality/astra",
      ~p"/lokality/jelenovska",
      ~p"/lokality/lites",
      ~p"/lokality/lubenec",
      ~p"/lokality/maj",
      ~p"/lokality/plesivka",
      ~p"/lokality/palkovicke-hurky",
      ~p"/lokality/pramen",
      ~p"/lokality/radost",
      ~p"/lokality/energetik",
      ~p"/lokality/tetrevi-boudy",
      ~p"/lokality/vlasim",
      ~p"/lokality/vysocina",
      ~p"/lokality/bystre",
      ~p"/lokality/brandys",
      ~p"/lokality/horni-becva-duo",
      ~p"/lokality/rousarka",
      ~p"/lokality/lugsteinhof",
      ~p"/lokality/u-kurtu",
      ~p"/lokality/u-medveda",
      ~p"/lokality/fontana",
      ~p"/lokality/na-mulde",
      ~p"/lokality/horni-pramen",
      ~p"/mail",
      ~p"/desk",
      ~p"/ft/blog",
      ~p"/blog",
      ~p"/blog/sablony",
      ~p"/blog/shrnuti-23",
      ~p"/blog/socci",
      ~p"/blog/v-tymu",
      ~p"/blog/plavecke-dovednosti",
      ~p"/blog/ti-co-uci"
      ###################################### old
      ### ~p"/zs/kontakty",
      ### ~p"/zs/kontakty-formular",
      ### ~p"/zs/o-nas",
      ### ~p"/zs/plavani/o-nas",
      ### ~p"/zs/o-nas/historie",
      ### ~p"/zs/plavani/o-nas/historie",
      ### ~p"/zs/o-nas/lide",
      ### ~p"/zs/plavani/o-nas/lide",
      ### ~p"/zs/o-nas/spolecnost",
      ### ~p"/zs/plavani/o-nas/spolecnost",
      ### ~p"/zs/lyzovani/about",
      ### ~p"/zs/enviro/about",
      ### ~p"/zs/vylety/about",
      ### ~p"/zs/doma/about",
      ### ~p"/zs/academy/about",
      ### ~p"/zs/reference",
      ### ~p"/zs/academy",
      ### ~p"/zs/academy/courses",
      ### ~p"/zs/courses/school",
      ### ~p"/zs/lokality",
      ### ~p"/zs/plavani/lokality",
      ### ~p"/zs/lyzovani/lokality",
      ### ~p"/zs/enviro/lokality",
      ### ~p"/zs/doma",
      ### ~p"/zs/doma/courses",
      ### ~p"/zs/enviro",
      ### ~p"/zs/enviro/courses",
      ### ~p"/zs/lyzovani",
      ### ~p"/zs/lyzovani/courses",
      ### ~p"/zs/plavani",
      ### ~p"/zs/plavani/verejnost",
      ### ~p"/zs/plavani/skolni-pobytovy-plavecky-kurz",
      ### ~p"/zs/plavani/predskolni-plavecky-kurz",
      ### ~p"/zs/plavani/primestsky-skolni-plavecky-kurz",
      ### ~p"/zs/plavani/sobotni-kurzy-plavani",
      ### ~p"/zs/plavani/services/pravidelne-kurzy-plavani/",
      ### ~p"/zs/plavani/summer-camp",
      ### ~p"/zs/plavani/letni-primestske-tabory",
      ### ~p"/zs/plavani/services/letni-primestske-tabory/",
      ### ~p"/zs/plavani/services/letni-tabor/",
      ### ~p"/zs/plavani/individualni-kurzy",
      ### ~p"/zs/plavani/services/vikendove-primestske-tabory-plavani/",
      ### ~p"/zs/lyzovani/skolni-lyzarsky-kurz",
      ### ~p"/zs/lyzovani/bezky",
      ### ~p"/zs/lyzovani/weekend",
      ### ~p"/zs/vylety",
      ### ~p"/zs/vylety/priroda/aves-brandysek",
      ### ~p"/zs/vylety/priroda/centrum-jaromer",
      ### ~p"/zs/vylety/priroda/ekocentrum-huslik",
      ### ~p"/zs/vylety/priroda/ekocentrum-hulice",
      ### ~p"/zs/vylety/priroda/stanice-hrachov",
      ### ~p"/zs/vylety/priroda/motylarium-votice",
      ### ~p"/zs/vylety/priroda/ekocentrum-vlasim",
      ### ~p"/zs/vylety/priroda/kurz-remesel",
      ### ~p"/zs/enviro/svp",
      ### ~p"/zs/enviro/tym",
      ### ~p"/zs/enviro/ss-tym",
      ### ~p"/zs/enviro/letni-pobytove-tabory",
      ### ~p"/zs/enviro/letni-primestske-tabory-v-tymu",
      ### ~p"/zs/enviro/primestske-tabory-enviro",
      ### ~p"/zs/enviro/evp",
      ### ~p"/zs/aktivity",
      ### ~p"/zs/ratings",
      ### ~p"/zs/vylety/courses",
      ### ~p"/zs/vylety/berlin",
      ### ~p"/zs/vylety/boleslav",
      ### ~p"/zs/vylety/drazdany",
      ### ~p"/zs/vylety/kutna-hora",
      ### ~p"/zs/vylety/mnichov",
      ### ~p"/zs/vylety/osvetim",
      ### ~p"/zs/vylety/praha",
      ### ~p"/zs/vylety/tabor",
      ### ~p"/zs/vylety/terezin",
      ### ~p"/zs/vylety/viden",
      ### ~p"/zs/lokality/agri",
      ### ~p"/zs/lokality/astra",
      ### ~p"/zs/lokality/jelenovska",
      ### ~p"/zs/lokality/lites",
      ### ~p"/zs/lokality/lubenec",
      ### ~p"/zs/lokality/maj",
      ### ~p"/zs/lokality/plesivka",
      ### ~p"/zs/lokality/palkovicke-hurky",
      ### ~p"/zs/lokality/pramen",
      ### ~p"/zs/lokality/radost",
      ### ~p"/zs/lokality/energetik",
      ### ~p"/zs/lokality/tetrevi-boudy",
      ### ~p"/zs/lokality/vlasim",
      ### ~p"/zs/lokality/vysocina",
      ### ~p"/zs/lokality/bystre",
      ### ~p"/zs/lokality/brandys",
      ### ~p"/zs/lokality/horni-becva-duo",
      ### ~p"/zs/lokality/rousarka",
      ### ~p"/zs/lokality/lugsteinhof",
      ### ~p"/zs/lokality/u-kurtu",
      ### ~p"/zs/lokality/u-medveda",
      ### ~p"/zs/lokality/fontana",
      ### ~p"/zs/lokality/na-mulde",
      ### ~p"/zs/lokality/horni-pramen",
      ### ~p"/404"
      #######################################
    ]
  end

  defmacro today do
    quote do
      Date.utc_today()
    end
  end

  def show_pages do
    for path <- pages() do
      route = "https://zsprodeti.cz" <> path

      """
      <url>
        <loc>#{route}</loc>
        <lastmod>#{today()}</lastmod>
        <priority>0.5</priority>
        <changefreq>weekly</changefreq>
      </url>
      """
    end
  end
end
