import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :flashtones, FlashtonesWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :flashtones, FlashtonesWeb.Endpoint,
  debug_errors: false,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000]

# http: [ip: {0, 0, 0, 0}, port: 4001]

# check_origin: ["http://www.zsprodeti.cz", "http://flashtones.cz"]

# https: [
#         port: 443,
#         cipher_suite: :strong,
#         otp_app: :flashtones,
#         keyfile: "/etc/letsencrypt/live/www.zsenviro.cz/fullchain.pem",
#         certfile: "/etc/letsencrypt/live/www.zsenviro.cz/privkey.pem"
#         # OPTIONAL Key for intermediate certificates:
#         # cacertfile: System.get_env("CACERTFILE")
#        ]
# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Flashtones.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# # Do not print debug messages in production
# config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
